from tkinter import filedialog, Toplevel
import tkinter as tk
import os
import threading
import subprocess
from functions import upload_file, save_to, start_processing
import functions

## UI ##


# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"E:\Documents\GitHub\Auto-Cut-Pauses-4Video\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x714")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 714,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    309.0,
    715.0,
    fill="#323232",
    outline="")

canvas.create_text(
    26.0,
    43.0,
    anchor="nw",
    text="Silence Trimmer",
    fill="#FFFFFF",
    font=("Inter Bold", 32 * -1)
)

canvas.create_rectangle(
    331.0,
    20.0,
    1416.0,
    689.0,
    fill="#631E8B",
    outline="")

canvas.create_rectangle(
    906.0,
    43.0,
    1384.0,
    661.0,
    fill="#974FFB",
    outline="")

canvas.create_rectangle(
    614.0,
    112.0,
    878.0,
    244.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    614.0,
    284.0,
    878.0,
    416.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    28.0,
    555.0,
    281.0,
    689.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    92.0,
    661.0,
    anchor="nw",
    text="By: Baxter David",
    fill="#1A1A1A",
    font=("Inter", 16 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    156.0,
    609.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=350.0,
    y=112.0,
    width=264.0,
    height=132.0
)

# Store these in variables so we can update them later
video_path_text_id = canvas.create_text(
    625.0,  # small left margin from 614.0
    155.0,
    anchor="nw",
    text="No File Selected",
    fill="#474747",
    font=("Ramabhadra", 24 * -1),
    width=240  # wrapping limit slightly less than 264
)

save_path_text_id = canvas.create_text(
    625.0,
    327.0,
    anchor="nw",
    text="No Save Location",
    fill="#474747",
    font=("Ramabhadra", 24 * -1),
    width=240
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=350.0,
    y=284.0,
    width=264.0,
    height=132.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=482.0,
    y=510.0,
    width=264.0,
    height=99.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=28.0,
    y=112.0,
    width=253.0,
    height=318.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=28.0,
    y=442.0,
    width=253.0,
    height=102.0
)



functions.terminal_box = Text(window, width=57, height=37, bg="#F0F0F0", fg="#1A1A1A")
functions.terminal_box.place(x=916, y=53)
functions.btn_upload = button_1
functions.btn_save_to = button_2
functions.btn_process = button_3
functions.lbl_video_path = tk.Label(window)
functions.lbl_save_path = tk.Label(window)


functions.terminal_box.place(x=916, y=53)
functions.lbl_video_path.place(x=620, y=160)
functions.lbl_save_path.place(x=620, y=330)


# Hook buttons to functions
button_1.configure(command=lambda: upload_file(canvas, video_path_text_id))
button_2.configure(command=lambda: save_to(canvas, save_path_text_id))
button_3.configure(command=start_processing)

window.resizable(False, False)
window.mainloop()



